java:
  image: 'https://hmctspublic.azurecr.io/sscs/ccd-callback-orchestrator:latest'
  applicationPort: 8070
  readinessPath: '/health/readiness'
  aadIdentityName: sscs
  ingressHost: sscs-ccd-callback-orchestrator-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    sscs:
      resourceGroup: sscs
      secrets:
        - name: idam-api
          alias: IDAM_URL
        - name: idam-sscs-systemupdate-user
          alias: IDAM_SSCS_SYSTEMUPDATE_USER
        - name: idam-sscs-systemupdate-password
          alias: IDAM_SSCS_SYSTEMUPDATE_PASSWORD
        - name: idam-sscs-oauth2-client-secret
          alias: IDAM_OAUTH2_CLIENT_SECRET
        - name: sscs-s2s-secret
          alias: IDAM_S2S_AUTH_TOTP_SECRET
        - name: s2s-micro
          alias: IDAM_S2S_AUTH_MICROSERVICE
        - name: evidence-share-topic-shared-access-key
          alias: AMQP_PASSWORD
  environment:
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: sscs-ccd-callback-orchestrator
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    IDAM_OAUTH2_CLIENT_ID: "sscs"
    TRUST_ALL_CERTS: "false"
    IDAM_S2S_AUTH: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_OAUTH2_REDIRECT_URL: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
    SUBSCRIPTION_NAME: "sscs-evidenceshare-subscription-{{ .Values.global.environment }}"
    TOPIC_NAME: "sscs-evidenceshare-topic-{{ .Values.global.environment }}"
    AMQP_HOST: "sscs-servicebus-{{ .Values.global.environment }}.servicebus.windows.net"
    AMQP_USERNAME: "SendAndListenSharedAccessKey"
