java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  aadIdentityName:
  readinessDelay: 90
  environment:
    SUBSCRIPTION_NAME: "sscs-evidenceshare-subscription-aat"
    TOPIC_NAME: "sscs-evidenceshare-topic-aat"
    AMQP_HOST: "sscs-servicebus-aat.servicebus.windows.net"
