java:
  image: 'https://hmctspublic.azurecr.io/sscs/ccd-callback-orchestrator:latest'
  applicationPort: 8070
  aadIdentityName: sscs
  ingressHost: sscs-ccd-callback-orchestrator-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    sscs:
      resourceGroup: sscs
      secrets:
        - idam-api
        - idam-oauth-user
        - idam-redirect
        - idam-sscs-systemupdate-user
        - idam-sscs-systemupdate-password
        - idam-sscs-oauth2-client-secret
        - idam-s2s-api
        - sscs-s2s-secret
        - s2s-micro
  environment:
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: sscs-ccd-callback-orchestrator
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    IDAM_OAUTH2_CLIENT_ID: "sscs"
