server:
  port: 8070

management:
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: ccd callback orchestrator

amqp:
  host: localhost
  username: guest
  password: guest
  topic: test.topic
  subscription: test.queue

idam:
  url: ${IDAM_URL:http://localhost:4501}
  s2s-auth:
    totp_secret: ${IDAM.S2S-AUTH.TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM.S2S-AUTH.MICROSERVICE:sscs}
    url: ${IDAM.S2S-AUTH:http://localhost:4502}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:SSCS_SYSTEM_UPDATE}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:SSCS_SYSTEM_UPDATE}
    client:
      id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
      secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirectUrl: ${IDAM_OAUTH2_REDIRECT_URL:https://localhost:9000/poc}


feign:
  client:
    config:
      core-case-data-api:
        decode404: true
