server:
  port: 8070

management:
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: ccd callback orchestrator

amqp:
  host: localhost
  username: guest
  password: guest
  topic: test.topic
  subscription: test.queue
