server:
  port: 8070

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /

spring:
  application:
    name: Ccd Callback Orchestrator

amqp:
  host: ${AMQP_HOST:localhost}
  username: ${AMQP_USERNAME:guest}
  password: ${AMQP_PASSWORD:guest}
  topic: ${TOPIC_NAME:test.topic}
  subscription: ${SUBSCRIPTION_NAME:test.queue}
  # DO NOT SET THIS 'true' IN PRODUCTION!
  trustAllCerts: ${TRUST_ALL_CERTS:true}

idam:
  url: ${IDAM_URL:http://localhost:5000}
  s2s-auth:
    totp_secret: ${IDAM_S2S_AUTH_TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM_S2S_AUTH_MICROSERVICE:sscs}
    url: ${IDAM_S2S_AUTH:http://localhost:4502}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:system.update@hmcts.net}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:Pa55word11}
    client:
      id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
      secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirectUrl: ${IDAM_OAUTH2_REDIRECT_URL:https://localhost:3000/authenticated}
    jwkUrl: ${IDAM_API_JWK_URL:http://localhost:5000/jwks}
  api:
    url: ${IDAM_URL:http://localhost:5000}
  client:
    id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
    secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirect_uri: ${IDAM_OAUTH2_REDIRECT_URL:https://localhost:3000/authenticated}


feign:
  client:
    config:
      core-case-data-api:
        decode404: true

springdoc:
  packagesToScan: "uk.gov.hmcts.reform.sscs.controllers"
