apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SERVICE_NAME}
  template:
    metadata:
      labels:
        app: ${SERVICE_NAME}
    spec:
      containers:
        - image: ${IMAGE_NAME}
          name: ${SERVICE_NAME}
          ports:
            - containerPort: 8070
          env:
            - name: IDAM_API_URL
              value: ${IDAM_API_URL}
            - name: IDAM_S2S_AUTH_TOTP_SECRET
              value: ${IDAM_S2S_AUTH_TOTP_SECRET}
            - name: IDAM_S2S_AUTH
              value: ${IDAM_S2S_AUTH}
            - name: IDAM_S2S_AUTH_MICROSERVICE
              value: ${IDAM_S2S_AUTH_MICROSERVICE}
            - name: IDAM_SSCS_SYSTEMUPDATE_USER
              value: ${IDAM_SSCS_SYSTEMUPDATE_USER}
            - name: IDAM_SSCS_SYSTEMUPDATE_PASSWORD
              value: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD}
            - name: IDAM_OAUTH2_CLIENT_ID
              value: "sscs"
            - name: IDAM_OAUTH2_CLIENT_SECRET
              value: ${IDAM_OAUTH2_CLIENT_SECRET}
            - name: IDAM_OAUTH2_REDIRECT_URL
              value: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
            - name: TRUST_ALL_CERTS
              value: "true"
            - name: SUBSCRIPTION_NAME
              value: "sscs-evidenceshare-subscription-aat"
            - name: TOPIC_NAME
              value: "sscs-evidenceshare-topic-aat"
            - name: AMQP_HOST
              value: "sscs-servicebus-aat.servicebus.windows.net"
            - name: AMQP_USERNAME
              value: "SendAndListenSharedAccessKey"
            - name: AMQP_PASSWORD
              value: ${AMQP_PASSWORD}
          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: "2500m"

          readinessProbe:
            timeoutSeconds: 10
            initialDelaySeconds: 30
            periodSeconds: 10
            httpGet:
              path: /health
              port: 8970
---
apiVersion: v1
kind: Service
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  labels:
    app: ${SERVICE_NAME}
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8970
  selector:
    app: ${SERVICE_NAME}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${SERVICE_NAME}
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: ${SERVICE_FQDN}
      http:
        paths:
          - path: /
            backend:
              serviceName: ${SERVICE_NAME}
              servicePort: 80
